import readline from "node:readline"
import requestProposal from "./utils/requestProposal.js"
import prompt from "./utils/prompt.js"
import generateProposal from "./utils/generateProposal.js"
import type { ParseProposal } from "./types.js"
import generateCode from "./utils/generateCode.js"

console.log('Chat started. Enter "exit" to quit.')

async function chat(){
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  })

  let isProposalAccepted = false
  let acceptedProposal: ParseProposal = {title:'',description:'',files:[],constraints:[],errors:[]}

  while(!isProposalAccepted){
    const input = await prompt(rl, 'What are we building?')
    const validatedProposal = await generateProposal(input)
    if(typeof validatedProposal === 'string'){
      console.log('Proposal could not be validated. Please reword your original prompt.')
    }else{
      console.log('The model generated the folliwing validated proposal:')
      console.log(validatedProposal)
      const isApproved = await prompt(rl, 'Do you approve this proposal? [y/n]')
      if(isApproved == 'y' || isApproved == 'Y' || isApproved == 'Yes' || isApproved == 'yes'){
        isProposalAccepted = true
        acceptedProposal = validatedProposal
      }else{
        console.log('The proposal was rejected. Try a new prompt.')
      }
    }
  }

  if(acceptedProposal.files.length > 0){
    const firstFile = acceptedProposal.files[1]
    const fileGenerated = await generateCode(firstFile, acceptedProposal)
    console.log('Code generated by DeepSeek:')
    console.log(fileGenerated)
  }else{
    console.log('Proposal didn\'t include files.')
  }
  rl.close()
  console.log('Agent exiting process. Goodbye!')
}

chat()
